version: '2'
services:
  andelackan:
    container_name: andelackan
    build: ./
    entrypoint: /docker-entrypoint.sh
    depends_on:
      - postgres
      - solr
    ports:
       - "5000:5000"
    environment:
       DATABASE_URL: "postgresql://ckan:ckan@postgres:5432/ckan"
       SOLR_URL: "http://solr:8983/solr/ckan"

  postgres:
    image: ckan/postgresql:latest
  solr:
    image: milafrerichs/ckan_solr
  redis:
    image: redis:latest
